### ISSUE TITLE
Add block for large images

### ISSUE THREAD

**Issue by brianmaierjr** [thelearninghouse/starter-theme#45]
max-width 1800px

max-size 500k

**Comment by kurtrank** [comment]
We've added `tlh_max_image_size()` in `inc/setup.php` that checks for image file size and width on upload and stops it if it's too large. Right now they are set to 1600px and 300 KB; they're defined right in the function if they must be changed. I think those sizes have been working pretty well for now, but we can see if they should change in the future.
