### ISSUE TITLE
Launch LP's

### ISSUE THREAD

**Issue by Lopesilvero** [thelearninghouse/starter-theme#7]
* Need theme name to be same across all schools for easy deployment of theme. Theme name used in paths in multiple files
  * Launch LP Stylesheet Reference
* Launch LP field name for accreditation changed from *color_3* to *accreditation_bg*
* Change field name for Launch LP Single Logo Version - same as custom page formatting.
* Make phone number color and icon color customizable per page.
* Move closing div for class *accred_images* inside php if statement

**Comment by brianmaierjr** [comment]
Are these resolved?
