### ISSUE TITLE
Add GTM

### ISSUE THREAD

**Issue by brianmaierjr** [thelearninghouse/starter-theme#9]
Add GTM in header of single and thank you page.

Make GTM ID a global site setting.

**Comment by kurtrank** [comment]
It's added as a global setting, but I still need to add it into the page templates.

**Comment by brianmaierjr** [comment]
This goes at the bottom of the head


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-N5NXX7');</script>



This goes directly after the opening body tag.


<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N5NXX7" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by kurtrank** [comment]
Should I go ahead and add this to header.php for all pages? At the moment I've added it to the LPs and the Launch LPs template.

**Comment by kurtrank** [comment]
I've added this in to the main `header.php`. It checks to see if `gtm_id` exists and prints that in the appropriate spots in the <script> and <iframe>.
